### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by patbenatar** [patbenatar/rbexy#55]
- [x] New method of providing a ComponentResolver at compile time instead of a provider at runtime
- [x] How to customize Rbexy.configuration.component_rendering_templates for other libs like ViewComponent
- [x] Namespaced component resolution #54 
- [x] `<Rbexy.Cache>` and dependency tracker #67 
- [x] AST Transforms API w/ example use case for CSS Modules #64 
- [x] `render(&block)` -> `render_in(context, &block)` rename
